"""initial schema

Revision ID: 1350e067643a
Revises: 
Create Date: 2026-02-19 13:14:32.837293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1350e067643a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_migrations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('applied_at', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename')
    )
    op.create_table('core_alert_channels',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('channel_type', sa.Text(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('min_severity', sa.Text(), nullable=False),
    sa.Column('domains', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('throttle_minutes', sa.Integer(), nullable=False),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('core_alert_throttle',
    sa.Column('dedup_key', sa.Text(), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(), nullable=False),
    sa.Column('send_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('dedup_key')
    )
    op.create_table('core_calc_dependencies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('calc_domain', sa.Text(), nullable=False),
    sa.Column('calc_operation', sa.Text(), nullable=False),
    sa.Column('calc_table', sa.Text(), nullable=True),
    sa.Column('depends_on_domain', sa.Text(), nullable=False),
    sa.Column('depends_on_table', sa.Text(), nullable=False),
    sa.Column('dependency_type', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('core_data_readiness',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain', sa.Text(), nullable=False),
    sa.Column('partition_key', sa.Text(), nullable=False),
    sa.Column('is_ready', sa.Integer(), nullable=False),
    sa.Column('ready_for', sa.Text(), nullable=True),
    sa.Column('all_partitions_present', sa.Integer(), nullable=False),
    sa.Column('all_stages_complete', sa.Integer(), nullable=False),
    sa.Column('no_critical_anomalies', sa.Integer(), nullable=False),
    sa.Column('dependencies_current', sa.Integer(), nullable=False),
    sa.Column('age_exceeds_preliminary', sa.Integer(), nullable=False),
    sa.Column('blocking_issues', sa.JSON(), nullable=True),
    sa.Column('certified_at', sa.DateTime(), nullable=True),
    sa.Column('certified_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('core_database_connections',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('dialect', sa.Text(), nullable=False),
    sa.Column('host', sa.Text(), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('database', sa.Text(), nullable=False),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('password_ref', sa.Text(), nullable=True),
    sa.Column('pool_size', sa.Integer(), nullable=False),
    sa.Column('max_overflow', sa.Integer(), nullable=False),
    sa.Column('pool_timeout', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('last_connected_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_error_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('core_executions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('workflow', sa.Text(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('lane', sa.Text(), nullable=False),
    sa.Column('trigger_source', sa.Text(), nullable=False),
    sa.Column('logical_key', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('parent_execution_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_execution_id'], ['core_executions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('core_expected_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain', sa.Text(), nullable=False),
    sa.Column('workflow', sa.Text(), nullable=False),
    sa.Column('schedule_type', sa.Text(), nullable=False),
    sa.Column('cron_expression', sa.Text(), nullable=True),
    sa.Column('partition_template', sa.Text(), nullable=False),
    sa.Column('partition_values', sa.JSON(), nullable=True),
    sa.Column('expected_delay_hours', sa.Integer(), nullable=True),
    sa.Column('preliminary_hours', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('core_schedules',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('target_type', sa.Text(), nullable=False),
    sa.Column('target_name', sa.Text(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('schedule_type', sa.Text(), nullable=False),
    sa.Column('cron_expression', sa.Text(), nullable=True),
    sa.Column('interval_seconds', sa.Integer(), nullable=True),
    sa.Column('run_at', sa.DateTime(), nullable=True),
    sa.Column('timezone', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('max_instances', sa.Integer(), nullable=False),
    sa.Column('misfire_grace_seconds', sa.Integer(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_status', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('core_sources',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('domain', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('core_anomalies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain', sa.Text(), nullable=False),
    sa.Column('workflow', sa.Text(), nullable=True),
    sa.Column('partition_key', sa.Text(), nullable=True),
    sa.Column('stage', sa.Text(), nullable=True),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=True),
    sa.Column('affected_records', sa.Integer(), nullable=True),
    sa.Column('sample_records', sa.JSON(), nullable=True),
    sa.Column('execution_id', sa.Text(), nullable=True),
    sa.Column('batch_id', sa.Text(), nullable=True),
    sa.Column('capture_id', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['core_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('core_concurrency_locks',
    sa.Column('lock_key', sa.Text(), nullable=False),
    sa.Column('execution_id', sa.Text(), nullable=False),
    sa.Column('acquired_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['core_executions.id'], ),
    sa.PrimaryKeyConstraint('lock_key')
    )
    op.create_table('core_dead_letters',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('execution_id', sa.Text(), nullable=False),
    sa.Column('workflow', sa.Text(), nullable=False),
    sa.Column('params', sa.JSON(), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_retry_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['core_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('core_execution_events',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('execution_id', sa.Text(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('data', sa.JSON(), server_default=sa.text("'{}'"), nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['core_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('core_manifest',
    sa.Column('domain', sa.Text(), nullable=False),
    sa.Column('partition_key', sa.Text(), nullable=False),
    sa.Column('stage', sa.Text(), nullable=False),
    sa.Column('stage_rank', sa.Integer(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('metrics_json', sa.JSON(), nullable=True),
    sa.Column('execution_id', sa.Text(), nullable=True),
    sa.Column('batch_id', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['core_executions.id'], ),
    sa.PrimaryKeyConstraint('domain', 'partition_key', 'stage')
    )
    op.create_table('core_quality',
    sa.Column('rowid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain', sa.Text(), nullable=False),
    sa.Column('partition_key', sa.Text(), nullable=False),
    sa.Column('check_name', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('actual_value', sa.Text(), nullable=True),
    sa.Column('expected_value', sa.Text(), nullable=True),
    sa.Column('details_json', sa.JSON(), nullable=True),
    sa.Column('execution_id', sa.Text(), nullable=False),
    sa.Column('batch_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['core_executions.id'], ),
    sa.PrimaryKeyConstraint('rowid')
    )
    op.create_table('core_rejects',
    sa.Column('rowid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain', sa.Text(), nullable=False),
    sa.Column('partition_key', sa.Text(), nullable=False),
    sa.Column('stage', sa.Text(), nullable=False),
    sa.Column('reason_code', sa.Text(), nullable=False),
    sa.Column('reason_detail', sa.Text(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('record_key', sa.Text(), nullable=True),
    sa.Column('source_locator', sa.Text(), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('execution_id', sa.Text(), nullable=False),
    sa.Column('batch_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['core_executions.id'], ),
    sa.PrimaryKeyConstraint('rowid')
    )
    op.create_table('core_schedule_locks',
    sa.Column('schedule_id', sa.Text(), nullable=False),
    sa.Column('locked_by', sa.Text(), nullable=False),
    sa.Column('locked_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['core_schedules.id'], ),
    sa.PrimaryKeyConstraint('schedule_id')
    )
    op.create_table('core_source_cache',
    sa.Column('cache_key', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=True),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('source_locator', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('content_size', sa.Integer(), nullable=False),
    sa.Column('content_path', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('etag', sa.Text(), nullable=True),
    sa.Column('last_modified', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['core_sources.id'], ),
    sa.PrimaryKeyConstraint('cache_key')
    )
    op.create_table('core_work_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain', sa.Text(), nullable=False),
    sa.Column('workflow', sa.Text(), nullable=False),
    sa.Column('partition_key', sa.Text(), nullable=False),
    sa.Column('params_json', sa.JSON(), nullable=True),
    sa.Column('desired_at', sa.DateTime(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_error_at', sa.DateTime(), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('current_execution_id', sa.Text(), nullable=True),
    sa.Column('latest_execution_id', sa.Text(), nullable=True),
    sa.Column('locked_by', sa.Text(), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['current_execution_id'], ['core_executions.id'], ),
    sa.ForeignKeyConstraint(['latest_execution_id'], ['core_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('core_workflow_runs',
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('workflow_name', sa.Text(), nullable=False),
    sa.Column('workflow_version', sa.Integer(), nullable=False),
    sa.Column('domain', sa.Text(), nullable=True),
    sa.Column('partition_key', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('outputs', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('error_category', sa.Text(), nullable=True),
    sa.Column('error_retryable', sa.Integer(), nullable=True),
    sa.Column('total_steps', sa.Integer(), nullable=False),
    sa.Column('completed_steps', sa.Integer(), nullable=False),
    sa.Column('failed_steps', sa.Integer(), nullable=False),
    sa.Column('skipped_steps', sa.Integer(), nullable=False),
    sa.Column('triggered_by', sa.Text(), nullable=False),
    sa.Column('parent_run_id', sa.Text(), nullable=True),
    sa.Column('schedule_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('capture_id', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_run_id'], ['core_workflow_runs.run_id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['core_schedules.id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('core_alerts',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('domain', sa.Text(), nullable=True),
    sa.Column('execution_id', sa.Text(), nullable=True),
    sa.Column('run_id', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('error_category', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.Column('dedup_key', sa.Text(), nullable=True),
    sa.Column('capture_id', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['core_executions.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['core_workflow_runs.run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('core_schedule_runs',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('schedule_id', sa.Text(), nullable=False),
    sa.Column('schedule_name', sa.Text(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('run_id', sa.Text(), nullable=True),
    sa.Column('execution_id', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('skip_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['core_executions.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['core_workflow_runs.run_id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['core_schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('core_source_fetches',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=True),
    sa.Column('source_name', sa.Text(), nullable=False),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('source_locator', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=True),
    sa.Column('byte_count', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.Column('etag', sa.Text(), nullable=True),
    sa.Column('last_modified', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('error_category', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('execution_id', sa.Text(), nullable=True),
    sa.Column('run_id', sa.Text(), nullable=True),
    sa.Column('capture_id', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['core_executions.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['core_workflow_runs.run_id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['core_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('core_workflow_steps',
    sa.Column('step_id', sa.Text(), nullable=False),
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('step_name', sa.Text(), nullable=False),
    sa.Column('step_type', sa.Text(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('outputs', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('error_category', sa.Text(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('execution_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['core_executions.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['core_workflow_runs.run_id'], ),
    sa.PrimaryKeyConstraint('step_id')
    )
    op.create_table('core_alert_deliveries',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('alert_id', sa.Text(), nullable=False),
    sa.Column('channel_id', sa.Text(), nullable=False),
    sa.Column('channel_name', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('response_json', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['core_alerts.id'], ),
    sa.ForeignKeyConstraint(['channel_id'], ['core_alert_channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('core_workflow_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('step_id', sa.Text(), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('idempotency_key', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['core_workflow_runs.run_id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['core_workflow_steps.step_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('core_workflow_events')
    op.drop_table('core_alert_deliveries')
    op.drop_table('core_workflow_steps')
    op.drop_table('core_source_fetches')
    op.drop_table('core_schedule_runs')
    op.drop_table('core_alerts')
    op.drop_table('core_workflow_runs')
    op.drop_table('core_work_items')
    op.drop_table('core_source_cache')
    op.drop_table('core_schedule_locks')
    op.drop_table('core_rejects')
    op.drop_table('core_quality')
    op.drop_table('core_manifest')
    op.drop_table('core_execution_events')
    op.drop_table('core_dead_letters')
    op.drop_table('core_concurrency_locks')
    op.drop_table('core_anomalies')
    op.drop_table('core_sources')
    op.drop_table('core_schedules')
    op.drop_table('core_expected_schedules')
    op.drop_table('core_executions')
    op.drop_table('core_database_connections')
    op.drop_table('core_data_readiness')
    op.drop_table('core_calc_dependencies')
    op.drop_table('core_alert_throttle')
    op.drop_table('core_alert_channels')
    op.drop_table('_migrations')
    # ### end Alembic commands ###
